export { default as Contact } from './Contact'
export { default as Error404 } from './Error404'
export { default as Home } from './Home'
export { default as Research } from './Research'
export { default as Projects } from './Projects'
export { default as ProjectInfo } from './ProjectInfo'
export { default as CV } from './CV'
